Back-end/my_first_django_v2/mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'),
    path('search', views.search, name='search'),
    path('<slug:tag_slug>', views.post_list, name='post_list_by_tag')

]

Back-end/my_first_django_v2/mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mysite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Back-end/my_first_django_v2/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    tags = TaggableManager()

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name="comments")
    body = models.TextField()
    name = models.CharField(max_length=80)
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

Back-end/my_first_django_v2/mysite/blog/forms.py
from django import forms
from .models import Comment, Post


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField(max_length=30, label='Search here:')

Back-end/my_first_django_v2/mysite/blog/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage,\
                                  PageNotAnInteger
from django.utils import timezone
from django.views.generic import ListView
from taggit.models import Tag
from .models import Post, Comment
from .forms import CommentForm, SearchForm

@login_required
def search(request):
    if request.method == 'GET':
        query = request.GET.get("query")
        results = Post.published.filter(title__contains=query) | Post.published.filter(body__contains=query)
        # title_query = Post.published.filter(title__contains=query)
        # body_query = Post.published.filter(body__contains=query)
        # results = title_query.union(body_query)
        return render(request,
                      'blog/post/search.html',
                      {'results': results,
                       'query':query}
                      )



@login_required
def post_list(request, tag_slug=None):

    num_visitas = request.session.get("num_visitas", 0)

    #num_visitas = int(request.COOKIES.get("num_visitas", 0))
    num_visitas += 1
    request.session["num_visitas"] = num_visitas
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    response = render(request,
                 'blog/post/list.html',
                 {'page': page,
                  'posts': posts,
                  'tag': tag})

    #response.set_cookie("num_visitas", num_visitas)
    return response

@login_required
def post_detail(request, year, month, day, post):
    last_visited_posts = request.session.get("last_visited_posts", [])
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    post_detail = [post.slug, year, month, day]
    found_post = False
    if len(last_visited_posts) > 5:
        last_visited_posts.pop()
    else:
        pass
    for n in last_visited_posts:
        if post.title in n.keys():
            i = last_visited_posts.index(n)
            last_visited_posts.pop(i)
            last_visited_posts.insert(0, {str(post): post_detail})
            found_post = True
        else:
            pass
    if not found_post:
        last_visited_posts.insert(0, {str(post): post_detail})

    request.session["last_visited_posts"] = last_visited_posts

    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST) # prepopular o fomulário com os dados do comentários
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect(post)
    elif request.method == 'GET':
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    response = render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comment_form': comment_form,
                   'new_comment': new_comment,
                    'similar_posts': similar_posts
                   })
    return response


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

Back-end/my_first_django_v2/mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|markdown }}

  <h2>Similar Posts</h2>
  {% for similar_post in similar_posts %}
  <p>
    <a href="{{ similar_post.get_absolute_url }}">{{similar_post.title}}</a>
    {% empty %}
    There are no similar posts yet.
  </p>

  {% endfor %}
  {% with post.comments.count as total_comments %}
  <h2>
    {{ total_comments }} Comment{{ total_comments | pluralize }}
  </h2>
  {% endwith %}
  {% for comment in post.comments.all %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>No comments here sis.</p>
  {% endfor %}
  {% if new_comment %}
    <h2>Your comment has been added.</h2>
  {% else %}
  <h2>Add new comment.</h2>
  <form method="POST">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <p><input type="submit" value="Add Comment"></p>
  </form>
  {% endif %}
{% endblock %}

Back-end/my_first_django_v2/mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{post.get_absolute_url}}">{{post.title}}</a>
    </li>
    {% endfor %}
</ul>

Back-end/my_first_django_v2/mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
  <h1>My Blog</h1>
  {% if tag %}
    <h2>Posts tagged with: {{ tag.name }}</h2>
  {% endif %}
  {% for post in all_posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
      <p class="tags">
        Tags:
        {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{tag.name}}
        </a>
        {% if not forloop.last %},{% endif %}
        {% endfor %}
      </p>
    {% with post.comments.count as total_comments %}
    <h4>{{ total_comments }} Comment{{ total_comments | pluralize }}</h4>
    {% endwith %}
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

Back-end/my_first_django_v2/mysite/blog/templates/blog/post/search.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
  <div id="content">

<h1>Searched: "<em>{{query}}</em>"</h1>
{% for post in results %}
<div class="search">
    <h2>
        <a href="{{post.get_absolute_url}}">
            {{post.title}}
        </a>
    </h2>
    <p class="tags">
        Tags:
        {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{tag.name}}
        </a>
        {% if not forloop.last %},{% endif %}
        {% endfor %}
    </p>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
</div>
{% empty %}
<h3>No posts found here sis.</h3>
{% endfor %}
  </div>
  <div id="sidebar">
      <a href="/blog">Home</a>
    <h2>My blog</h2>
    <p>This is my blog.</p>
    <p>I've written {%total_posts%} posts</p>
    <h3>Latest Posts</h3>
    {% show_latest_posts 3 %}
    {% search_bar %}
  </form>
  </div>
</body>

Back-end/my_first_django_v2/mysite/blog/templates/blog/post/search_bar.html
<form action="{% url "blog:search" %}" method="GET">
    {{ search_form.as_p }}
    <input type="submit" value="Search">
</form>