Back-end/imbd_v3/imdb/accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
import django.contrib.auth.views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('profile/', views.show_profile, name='profile'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Back-end/imbd_v3/imdb/imdb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls', namespace='movies')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('shows/', include('shows.urls', namespace='shows')),
]

Back-end/imbd_v3/imdb/accounts/models.py
from django.conf import settings
from django.db import models
from movies.models import Movie
from staff.models import Actors

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="profile")
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    top_movies = models.ManyToManyField(Movie,
                                        blank=True,
                                        related_name="top_movies")
    top_actors = models.ManyToManyField(Actors,
                                        blank=True,
                                        related_name="top_actors")
    def __str__(self):
        return f'Profile for user {self.user.username}'

Back-end/imbd_v3/imdb/accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo', 'top_movies')

Back-end/imbd_v3/imdb/accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from .models import Profile
from movies.models import Movie


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated '\
                                        'successfully')
                else:
                    return HttpResponse('Disabled accounts')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            # Create the user profile
            Profile.objects.create(user=new_user)
            return render(request,
                          'accounts/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'accounts/register.html',
                  {'user_form': user_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(
                                    instance=request.user.profile,
                                    data=request.POST,
                                    files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            # messages.success(request, 'Profile updated successfully')
        else:
            # messages.error(request, 'Error updating your profile')
            pass
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,
                  'accounts/edit.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})


@login_required
def show_profile(request):
    if request.method == 'GET':
        user_data = request.user
        profile_data = request.user.profile
        recently_seen = request.session.get('recently_seen_movies', [])
        movie_list = Movie.objects.all()
        recently_seen_movies = []
        for movie in movie_list:
            for rec_id in recently_seen:
                if movie.id == rec_id:
                    recently_seen_movies.append(movie.title)
                else:
                    pass
    else:
        pass
    return render(request,
                  'accounts/profile.html',
                  {'user_data': user_data,
                   'profile_data': profile_data,
                   'recently_seen_movies': recently_seen_movies})

Back-end/imbd_v3/imdb/accounts/templates/accounts/edit.html
{% extends "movies/base.html" %}

{% block title %}Edit your account{% endblock %}

{% block content %}
  <h1>Edit your account</h1>
  <p>You can edit your account using the following form:</p>
  <form method="post" enctype="multipart/form-data">
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Save changes"></p>
  </form>
{% endblock %}

Back-end/imbd_v3/imdb/accounts/templates/accounts/login.html
{% extends "movies/base.html" %}

{% block title %}Log-in{% endblock %}

{% block content %}
  <h1>Log-in</h1>
  <p>Please, use the following form to log-in:</p>
  <form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Log in"></p>
  </form>
{% endblock %}

Back-end/imbd_v3/imdb/accounts/templates/accounts/profile.html
{% extends "movies/base.html" %}

{% block title %}This is your account{% endblock %}

{% block content %}
    <h1>This is your account</h1>
    <h3>Welcome, {{user_data.username}}</h3>
    {% if profile_data.photo %}
        <img src={{profile_data.photo.url}} alt="imagem" />
    {% else %}
    <h3>You have missing data, please complete your profile.</h3>
    {% endif %}
    <h2>{{user_data.username}}'s recently watched movies:</h2>
    <ul>
        {% for mov in recently_seen_movies %}
        <li> {{mov.title}}</li>
        {% endfor %}
    </ul>
    <h2>{{user_data.username}}'s top movies:</h2>
    <ul>
        {% for mov in request.user.profile.top_movies.all %}
        <li> {{mov.title}}</li>
        {% endfor %}
    </ul>
    <h2>{{user_data.username}}'s top actors:</h2>
    <ul>
        {% for act in request.user.profile.top_actors.all %}
        <li> {{act}}</li>
        {% endfor %}
    </ul>
    <h2>{{user_data.username}}'s critics made:</h2>
    <ul>
        {% for critic in user_data.critics.all %}
        <li>
            <h2>Critic for: <em>{{ critic.movie }}</em></h2>
            <h4>Critic done in {{ critic.created }}</h4>
            <p>{{ critic.critic|truncatewords:50 }}</p>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

Back-end/imbd_v3/imdb/accounts/templates/accounts/register.html
{% extends "movies/base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
  <h1>Create an account</h1>
  <p>Please, sign up using the following form:</p>
  <form method="post">
    {{ user_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Create my account"></p>
  </form>
{% endblock %}

Back-end/imbd_v3/imdb/accounts/templates/accounts/register_done.html
{% extends "movies/base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
  <h1>Welcome {{ new_user.first_name }}!</h1>
  <p>Your account has been successfully created. Now you can <a href="{% url "accounts:login" %}">log in</a>.</p>
{% endblock %}