Back-end/imbd_v3/imdb/imdb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls', namespace='movies')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('shows/', include('shows.urls', namespace='shows')),
]

Back-end/imbd_v3/imdb/movies/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('<slug:tag_slug>', views.movie_list, name='movie_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:movie_slug>/', views.movie_detail, name='movie_detail'),
    path('search/', views.search, name='search'),
    path('what-to-watch/', views.what_to_watch, name='what-to-watch'),
    path('what-to-watch-rec/', views.what_to_watch_rec, name='what-to-watch-rec')
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Back-end/imbd_v3/imdb/movies/models.py
from django.db import models
from django.urls import reverse
from staff.models import Actors, Writers, Producers
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class Movie(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(default="")
    description = models.TextField()
    rating = models.FloatField()
    duration = models.CharField(max_length=8)
    tags = TaggableManager()
    release_date = models.DateField()
    actors = models.ManyToManyField(Actors)
    writers = models.ManyToManyField(Writers)
    producers = models.ManyToManyField(Producers)
    images = models.ImageField(upload_to='movies/%Y/%m/%d/', blank=True)

    def get_absolute_url(self):
        return reverse('movies:movie_detail',
                       args=[self.release_date.year,
                             self.release_date.month,
                             self.release_date.day,
                             self.slug])

    def __str__(self):
        return self.title


class Critics(models.Model):
    movie = models.ForeignKey(Movie,
                              on_delete=models.CASCADE,
                              related_name="critics")
    critic = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    rating = models.FloatField()
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name="critics")

    def __str__(self):
        return f'Critic to {self.movie} by {self.user}'

Back-end/imbd_v3/imdb/movies/forms.py
from django import forms
from .models import Critics
from django.core.exceptions import ValidationError


class SearchForm(forms.Form):
    query = forms.CharField(max_length=30, label='Search here:')


class CriticForm(forms.ModelForm):
    class Meta:
        model = Critics
        fields = ('critic', 'rating')

    def clean(self):
        cleaned_data = super().clean()
        rating = cleaned_data.get('rating')
        if rating > 10 or rating < 1:
            raise forms.ValidationError('Rating needs to be between 1 and 10, not more, not less.')
        return cleaned_data

Back-end/imbd_v3/imdb/movies/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from taggit.models import Tag
from .models import Movie
from .forms import CriticForm


def search(request):
    if request.method == 'GET':
        query = request.GET.get("query")
        results = Movie.objects.filter(title__contains=query)

        return render(request,
                      'movies/movies/search.html',
                      {'results': results,
                       'query': query}
                      )


def movie_list(request, tag_slug=None):
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = Movie.objects.filter(tags__in=[tag])
    else:
        object_list = Movie.objects.all()
    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        movies = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        movies = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        movies = paginator.page(paginator.num_pages)
    return render(request,
                 'movies/movies/list.html',
                 {'page': page,
                  'movies': movies,
                  'tag': tag})


def movie_detail(request, movie_slug, year, month, day):
    movie = get_object_or_404(Movie, slug=movie_slug,
                                   release_date__year=year,
                                   release_date__month=month,
                                   release_date__day=day)
    critic_form = None
    new_critic = None

    list_ratings = []
    for crit in movie.critics.all():
        list_ratings.append(crit.rating)
    sum_of_crits = sum(list_ratings)
    print(list_ratings)

    if request.user.is_authenticated:
        recently_seen_movies = list(request.session.get('recently_seen_movies', []))
        if movie.id in recently_seen_movies:
            i = recently_seen_movies.index(movie.id)
            recently_seen_movies.pop(i)
        recently_seen_movies.insert(0, movie.id)
        if len(recently_seen_movies) > 3:
            recently_seen_movies.pop()
        request.session['recently_seen_movies'] = recently_seen_movies
        if request.method == 'POST':
            critic_form = CriticForm(data=request.POST)
            if critic_form.is_valid():
                new_critic = critic_form.save(commit=False)
                new_critic.movie = movie
                if len(list_ratings) == 0:
                    new_rating = (movie.rating + new_critic.rating)/2
                else:
                    new_rating = (new_critic.rating + sum_of_crits) / (1+len(list_ratings))
                movie.rating = new_rating
                movie.save()
                new_critic.user_id = request.user.id
                new_critic.save()
                return redirect(movie)
        elif request.method == 'GET':
            critic_form = CriticForm()
    else:
        pass
    print(movie.actors.all())
    response = render(request,
                  'movies/movies/detail.html',
                  {'movie': movie,
                   'critic_form': critic_form,
                   'new_critic': new_critic})

    return response


@login_required
def what_to_watch(request):
    user = request.user
    top_movies = list(user.profile.top_movies.all())
    movies_based_on_top = dict()
    for m in top_movies:
        for t in list(m.tags.all()):
            objects = Movie.objects.filter(tags__in=[t])
            for object in objects:
                if m.title in movies_based_on_top.keys():
                    if object in movies_based_on_top[str(m.title)]:
                        pass
                    else:
                        movies_based_on_top[str(m.title)].append(object)
                else:
                    movies_based_on_top[str(m.title)] = [object]
    return render(request,
                  'movies/movies/what_to_watch.html',
                  {'movies_based_on_top': movies_based_on_top})

def what_to_watch_rec(request):
    recently_seen = request.session.get('recently_seen_movies', [])
    movie_list = Movie.objects.all()
    recently_seen_movies = []
    for movie in movie_list:
        for rec_id in recently_seen:
            if movie.id == rec_id:
                recently_seen_movies.append(movie)
            else:
                pass
    movies_based_on_recent = dict()
    for m in recently_seen_movies:
        for t in list(m.tags.all()):
            objects = Movie.objects.filter(tags__in=[t])
            for object in objects:
                if m.title in movies_based_on_recent.keys():
                    if object in movies_based_on_recent[str(m.title)]:
                        pass
                    else:
                        movies_based_on_recent[str(m.title)].append(object)
                else:
                    movies_based_on_recent[str(m.title)] = [object]
    return render(request,
                  'movies/movies/what_to_watch_rec.html',
                  {'movies_based_on_recent': movies_based_on_recent})

Back-end/imbd_v3/imdb/movies/templates/movies/movies/detail.html
{% extends "movies/base.html" %}
{% load movies_tags %}

{% block title %}{{ movie.title }}{% endblock %}

{% block content %}
    <div class="movie-detail">
        <h1>{{ movie.title }}</h1>
        <h3 class="tags">{{ movie.duration }}  | {% for tag in movie.tags.all %} {{ tag.name }} {% endfor %} | Released in {{ movie.release_date }}</h3>
        <h3 class="rating">{{ movie.rating | round_num }} <i class="far fa-star"></i></h3>
        <img style="width:30%; height:50vh;" src={{movie.images.url}} alt="{{ movie.title }}" />
        <h3>Description:</h3>
        <p>{{ movie.description }}</p>
        <h3>Actors:</h3>
        {% for act in movie.actors.all %}
            <a href="{{act.details.get_absolute_url}}">{{act.details.name}} {{act.details.last_name}}</a>
        {% endfor %}
        <h3>Producers:</h3>
        {% for p in movie.producers.all %}
            <a href="{{p.details.get_absolute_url}}">{{p.details.name}} {{p.details.last_name}}</a>
        {% endfor %}
        <h3>Writers:</h3>
        {% for w in movie.actors.all %}
            <a href="{{w.details.get_absolute_url}}">{{w.details.name}} {{w.details.last_name}}</a>
        {% endfor %}
        <div class="critics">
            <h2>Critics:</h2>
            {% for critic in movie.critics.all %}
            <div class="critic">
              <h4 class="info">
                Critic {{ forloop.counter }} by {{ critic.user.username }} {{ critic.created }}
              </h4>
              {{ critic.critic |linebreaks }}
            </div>
            {% empty %}
            <p>No critics here sis.</p>
          {% endfor %}
        </div>
        {% if user.is_authenticated %}
        <div id="comment-form">
            <form method="POST">
            {% csrf_token %}
            {{ critic_form.as_p }}
            <p><input type="submit" value="Add Critic"></p>
          </form>
        </div>
        {% endif %}
    </div>
{% endblock %}

Back-end/imbd_v3/imdb/movies/templates/movies/movies/list.html
{% extends "movies/base.html" %}
{% load movies_tags %}

{% block title %}Movies{% endblock %}

{% block content %}
  <div class="list">
    <h1 class="head">IMDB</h1>
    <div id="Form">
      {% search_bar %}
    </div>
    {% for movie in movies %}
      <div class="movie">
        <h2>
          <a href="{{movie.get_absolute_url}}">{{ movie.title }}</a>
        </h2>
        <img id="trailer-image" src={{movie.images.url}} alt="{{ movie.title }}" />
        <p class="date">
          Released in: <em>{{ movie.release_date }}</em>
        </p>
        {% for tag in movie.tags.all %}
        <a href="{% url "movies:movie_list_by_tag" tag.slug %}">
          {{ tag }}{% if forloop.last %} {% else %} | {% endif %}
        </a>
        {% endfor %}
        <h3 class="rating">{{ movie.rating | round_num }} <i class="far fa-star"></i></h3>
        {{ movie.description|truncatewords:25|linebreaks }}
      </div>
    {% endfor %}
    {% include "pagination.html" with page=movies %}
  </div>
{% endblock %}

Back-end/imbd_v3/imdb/movies/templates/movies/movies/search.html
{% extends "movies/base.html" %}
{% load movies_tags %}

{% block title %}Movies{% endblock %}

{% block content %}
<h1>Searched for movies: "<em>{{query}}</em>"</h1>
    <div id="Form">
      {% search_bar %}
    </div>
{% for movie in results %}
<div class="search">
        <h2>
          <a href="{{movie.get_absolute_url}}">{{ movie.title }}</a>
        </h2>
        <img id="trailer-image" src={{movie.images.url}} alt="{{ movie.title }}" />
        <p class="date">
          Released in: <em>{{ movie.release_date }}</em>
        </p>
        <h3 class="rating">{{ movie.rating }} <i class="far fa-star"></i></h3>
        {{ movie.description|truncatewords:25|linebreaks }}
        </div>
        {% empty %}
        <h3>No movies found here sis.</h3>
        {% endfor %}
{% endblock %}

Back-end/imbd_v3/imdb/movies/templates/movies/movies/search_bar.html
<form action="{% url "movies:search" %}" method="GET">
    {{ search_form.as_p }}
    <input type="submit" value="Search">
</form>

Back-end/imbd_v3/imdb/movies/templates/movies/movies/what_to_watch.html
{% extends "movies/base.html" %}
{% load movies_tags %}

{% block title %}What To Watch{% endblock %}

{% block content %}
<div class="list">
    <h1>IMDB</h1>
    <div id="Form">
      {% search_bar %}
    </div>
    <div class="movies-like">
        <p>Based on top picks</p>
        <a href="{% url "movies:what-to-watch-rec" %}">Based on recently watched</a>
        <h2>Based on Top Picks:</h2>
        {% for movs, movies in movies_based_on_top.items %}
        <h2 id="movies-like">Movies like: <em>{{ movs }}</em></h2>
        {% for mov in movies %}
        <div class="movie">
            <h2 id="movie-title"><a href="{{mov.get_absolute_url}}">{{mov.title}}</a></h2>
            <img id="trailer-image" src={{mov.images.url}} alt="{{ mov.title }}" />
            <p class="date">
              Released in: <em>{{ mov.release_date }}</em>
            </p>
            <h3 class="rating">{{ mov.rating }} <i class="far fa-star"></i></h3>
            {{ mov.description|truncatewords:25|linebreaks }}
        </div>
        {% endfor %}
        {% endfor %}
    </div>
</div>
{% endblock %}

Back-end/imbd_v3/imdb/movies/templates/movies/movies/what_to_watch_rec.html
{% extends "movies/base.html" %}
{% load movies_tags %}

{% block title %}What To Watch{% endblock %}

{% block content %}
<div class="list">
    <h1>IMDB</h1>
    <div id="Form">
      {% search_bar %}
    </div>
    <div class="movies-like">
        <a href="{% url "movies:what-to-watch"%}">Based on top picks</a>
        <p>Based on recently watched</p>
        <h2>Based on recently watched:</h2>
        {% for movs, movies in movies_based_on_recent.items %}
        <h2 id="movies-like">Movies like: <em>{{ movs }}</em></h2>
        {% for mov in movies %}
        <div class="movie">
            <h2 id="movie-title"><a href="{{mov.get_absolute_url}}">{{mov.title}}</a></h2>
            <img id="trailer-image" src={{mov.images.url}} alt="{{ mov.title }}" />
            <p class="date">
              Released in: <em>{{ mov.release_date }}</em>
            </p>
            <h3 class="rating">{{ mov.rating }} <i class="far fa-star"></i></h3>
            {{ mov.description|truncatewords:25|linebreaks }}
        </div>
        {% endfor %}
        {% endfor %}
    </div>
</div>
{% endblock %}